

class EmployeeNotFoundError(Exception):
    pass


class PracticeNotFoundError(Exception):
    pass